(() => {
  const css = `video.mosuan-invert{filter:invert(.90) hue-rotate(180deg);}
.mosuan-coordinate-layer{position:absolute;z-index:2147483647;box-sizing:border-box;pointer-events:none;margin:0;padding:0;transform:none;overflow:visible;display:block;}
.mosuan-crop-ui,.mosuan-mask-ui{position:absolute;inset:0;display:none;box-sizing:border-box;pointer-events:none;}
.mosuan-crop-ui.show,.mosuan-mask-ui.show{display:block;pointer-events:auto;}
.mosuan-crop-ui::before,.mosuan-mask-ui::before{content:"";position:absolute;inset:0;box-shadow:0 0 0 9999px rgba(0,0,0,.46);pointer-events:none;}
.mosuan-crop-box{position:absolute;box-sizing:border-box;border:2px solid #ff5a36;cursor:move;min-width:3%;min-height:3%;}
.mosuan-mask-box{position:absolute;box-sizing:border-box;border:2px solid #ff5a36;background:rgba(26,26,26,.98);cursor:move;min-width:2%;min-height:2%;}
.mosuan-crop-handle,.mosuan-mask-handle{position:absolute;width:15px;height:15px;border-radius:50%;background:#ff5a36;border:2px solid #fff;box-sizing:border-box;}
.handle-nw{left:-8px;top:-8px;cursor:nwse-resize}.handle-ne{right:-8px;top:-8px;cursor:nesw-resize}.handle-sw{left:-8px;bottom:-8px;cursor:nesw-resize}.handle-se{right:-8px;bottom:-8px;cursor:nwse-resize}
.mosuan-crop-toolbar,.mosuan-mask-toolbar{position:absolute;left:50%;top:calc(100% + 12px);transform:translateX(-50%);display:flex;gap:7px;padding:7px;border-radius:9px;background:rgba(20,20,20,.94);box-shadow:0 4px 20px rgba(0,0,0,.35);white-space:nowrap;pointer-events:auto;}
.mosuan-crop-toolbar button,.mosuan-mask-toolbar button{border:0;border-radius:6px;padding:7px 12px;background:#333;color:#fff;font-size:13px;cursor:pointer;}
.mosuan-crop-toolbar button[data-a="restore"],.mosuan-mask-toolbar button[data-a="restore"]{background:#a73525;}
.mosuan-video-mask{position:absolute;z-index:2147483647;pointer-events:none;background:rgba(26,26,26,.98);}
.mosuan-crop-mask{position:absolute;inset:0;z-index:2147483645;pointer-events:none;display:none;background:transparent;}
.mosuan-crop-mask>div{position:absolute;background:#000;pointer-events:none;}`;
  const style=document.createElement('style'); style.id='mosuan-kiosk-style'; style.textContent=css;
  (document.head||document.documentElement).appendChild(style);
})();

(() => {
  const P={video:null,findVideo(){const list=[...document.querySelectorAll('video')].filter(v=>{const r=v.getBoundingClientRect();return r.width>120&&r.height>80;});if(!list.length)return null;list.sort((a,b)=>{const ra=a.getBoundingClientRect(),rb=b.getBoundingClientRect();return rb.width*rb.height-ra.width*ra.height;});return list[0];},bind(v){if(!v||this.video===v)return;this.video=v;window.dispatchEvent(new CustomEvent('mosuan:video',{detail:v}));},playPause(){if(!this.video)return;if(this.video.paused){const p=this.video.play();if(p?.catch)p.catch(()=>{});}else this.video.pause();},seek(s){if(!this.video||!Number.isFinite(this.video.duration))return;this.video.currentTime=Math.max(0,Math.min(this.video.duration,this.video.currentTime+s));},setRate(r){if(this.video)this.video.playbackRate=Math.max(.25,Math.min(4,r));},changeRate(d){if(!this.video)return;const rates=[.5,.75,1,1.25,1.5,1.75,2,2.5,3,4];let i=rates.reduce((b,x,j)=>Math.abs(x-this.video.playbackRate)<Math.abs(rates[b]-this.video.playbackRate)?j:b,0);i=Math.max(0,Math.min(rates.length-1,i+d));this.video.playbackRate=rates[i];},mute(){if(this.video)this.video.muted=!this.video.muted;}};
  window.MosuanPlayer=P;
})();

(() => {let enabled=false;function apply(v){if(v)v.classList.toggle('mosuan-invert',enabled);}window.MosuanInvert={toggle(){enabled=!enabled;apply(MosuanPlayer.video);return enabled;},set(v){enabled=!!v;apply(MosuanPlayer.video);},get(){return enabled;}};window.addEventListener('mosuan:video',e=>apply(e.detail));})();

(() => {
  const Coord={layer:null,host:null,video(){return window.MosuanPlayer?.video||null;},videoRect(){const v=this.video();if(!v)return null;const r=v.getBoundingClientRect();if(r.width<2||r.height<2)return null;return {left:r.left,top:r.top,width:r.width,height:r.height,right:r.right,bottom:r.bottom};},contentRect(v,r){const vw=v.videoWidth||0,vh=v.videoHeight||0,cs=getComputedStyle(v),fit=(cs.objectFit||'fill').toLowerCase();if(!vw||!vh||fit==='fill')return r;const ar=vw/vh,boxAr=r.width/r.height;let x=r.left,y=r.top,w=r.width,h=r.height;if(fit==='contain'||fit==='scale-down'){if(boxAr>ar){h=r.height;w=h*ar;x=r.left+(r.width-w)/2;}else{w=r.width;h=w/ar;y=r.top+(r.height-h)/2;}}else if(fit==='cover'){if(boxAr>ar){w=r.width;h=w/ar;y=r.top+(r.height-h)/2;}else{h=r.height;w=h*ar;x=r.left+(r.width-w)/2;}}return {left:x,top:y,width:w,height:h,right:x+w,bottom:y+h};},rect(){const v=this.video(),r=this.videoRect();return v&&r?this.contentRect(v,r):null;},getHost(){const fs=document.fullscreenElement||document.webkitFullscreenElement;if(fs&&fs!==this.video())return fs;return document.documentElement;},ensure(){const host=this.getHost();if(!this.layer){this.layer=document.createElement('div');this.layer.className='mosuan-coordinate-layer';}if(this.host!==host||this.layer.parentElement!==host){try{host.appendChild(this.layer);}catch(e){document.documentElement.appendChild(this.layer);}this.host=host;}return this.layer;},render(){const r=this.rect(),layer=this.ensure();if(!r){layer.style.display='none';return;}const host=this.host||document.documentElement,hr=host.getBoundingClientRect?host.getBoundingClientRect():{left:0,top:0};layer.style.display='block';layer.style.left=(r.left-hr.left)+'px';layer.style.top=(r.top-hr.top)+'px';layer.style.width=r.width+'px';layer.style.height=r.height+'px';layer.dataset.fullscreen=(host===document.fullscreenElement||host===document.webkitFullscreenElement)?'1':'0';window.dispatchEvent(new CustomEvent('mosuan:coordinate',{detail:{rect:r,videoRect:this.videoRect(),layer,host}}));}};
  window.MosuanCoord=Coord;let raf=0;function render(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;Coord.render();});}addEventListener('resize',render,{passive:true});addEventListener('scroll',render,true);addEventListener('orientationchange',render);document.addEventListener('fullscreenchange',()=>{render();requestAnimationFrame(()=>render());setTimeout(render,50);setTimeout(render,200);setTimeout(render,500);});document.addEventListener('webkitfullscreenchange',render);addEventListener('mosuan:video',()=>{render();setTimeout(render,100);});if(window.ResizeObserver)new ResizeObserver(render).observe(document.documentElement);setInterval(render,200);render();
})();

(() => {
  const state={editing:false,applied:false,x:0,y:0,w:1,h:1,draft:null};let overlay=null,box=null,toolbar=null,mode=null,start=null,original=null,cropMask=null;
  function ensure(){if(overlay)return;overlay=document.createElement('div');overlay.className='mosuan-crop-ui';box=document.createElement('div');box.className='mosuan-crop-box';['nw','ne','sw','se'].forEach(n=>{const h=document.createElement('div');h.className='mosuan-crop-handle handle-'+n;h.dataset.handle=n;box.appendChild(h);h.addEventListener('pointerdown',startHandle,true);});box.addEventListener('pointerdown',startMove,true);box.addEventListener('dblclick',commit,true);toolbar=document.createElement('div');toolbar.className='mosuan-crop-toolbar';toolbar.innerHTML='<button data-a="apply">确定裁切</button><button data-a="restore">恢复原视频</button><button data-a="cancel">取消</button>';toolbar.onclick=e=>{const a=e.target?.dataset?.a;if(a==='apply')commit();if(a==='restore')restore();if(a==='cancel')cancel();};overlay.append(box,toolbar);MosuanCoord.ensure().appendChild(overlay);cropMask=document.createElement('div');cropMask.className='mosuan-crop-mask';cropMask.innerHTML='<div></div><div></div><div></div><div></div>';MosuanCoord.ensure().appendChild(cropMask);}
  function render(){if(!overlay)return;const layer=MosuanCoord.ensure();if(overlay.parentElement!==layer)layer.appendChild(overlay);if(cropMask.parentElement!==layer)layer.appendChild(cropMask);const s=state.draft||state;overlay.style.inset='0';box.style.left=s.x*100+'%';box.style.top=s.y*100+'%';box.style.width=s.w*100+'%';box.style.height=s.h*100+'%';renderAppliedMask();}
  function renderAppliedMask(){if(!cropMask)return;const s=state,show=state.applied&&!state.editing;cropMask.style.display=show?'block':'none';if(!show)return;const right=1-s.x-s.w,bottom=1-s.y-s.h,t=cropMask.children[0],r=cropMask.children[1],b=cropMask.children[2],l=cropMask.children[3];t.style.cssText=`left:0;top:0;width:100%;height:${s.y*100}%`;l.style.cssText=`left:0;top:${s.y*100}%;width:${s.x*100}%;height:${s.h*100}%`;r.style.cssText=`left:${(s.x+s.w)*100}%;top:${s.y*100}%;width:${right*100}%;height:${s.h*100}%`;b.style.cssText=`left:0;top:${(s.y+s.h)*100}%;width:100%;height:${bottom*100}%`;}
  function startMove(e){if(!state.editing||e.target!==box)return;mode='move';start={x:e.clientX,y:e.clientY};original={...state.draft};e.preventDefault();e.stopPropagation();}function startHandle(e){if(!state.editing)return;mode=e.currentTarget.dataset.handle;start={x:e.clientX,y:e.clientY};original={...state.draft};e.preventDefault();e.stopPropagation();}
  function move(e){if(!mode||!start||!original||!state.editing)return;const r=MosuanCoord.rect();if(!r)return;const dx=(e.clientX-start.x)/r.width,dy=(e.clientY-start.y)/r.height,min=.03;let s={...original};if(mode==='move'){s.x=Math.max(0,Math.min(1-s.w,original.x+dx));s.y=Math.max(0,Math.min(1-s.h,original.y+dy));}else{if(mode.includes('w')){const right=original.x+original.w,nx=Math.max(0,Math.min(right-min,original.x+dx));s.x=nx;s.w=right-nx;}if(mode.includes('e')){const right=Math.max(original.x+min,Math.min(1,original.x+original.w+dx));s.w=right-original.x;}if(mode.includes('n')){const bottom=original.y+original.h,ny=Math.max(0,Math.min(bottom-min,original.y+dy));s.y=ny;s.h=bottom-ny;}if(mode.includes('s')){const bottom=Math.max(original.y+min,Math.min(1,original.y+original.h+dy));s.h=bottom-original.y;}}state.draft=s;render();}
  function end(){mode=null;start=null;original=null;}function apply(){ensure();renderAppliedMask();}function enter(){ensure();state.editing=true;state.draft={x:state.x,y:state.y,w:state.w,h:state.h};overlay.classList.add('show');cropMask.style.display='none';render();}function commit(){if(!state.editing)return;Object.assign(state,state.draft||{});state.draft=null;state.editing=false;state.applied=!(state.x<=.0001&&state.y<=.0001&&state.w>=.9999&&state.h>=.9999);overlay.classList.remove('show');apply();}function cancel(){state.draft=null;state.editing=false;overlay?.classList.remove('show');renderAppliedMask();}function restore(){state.x=0;state.y=0;state.w=1;state.h=1;state.draft=null;state.editing=false;state.applied=false;overlay?.classList.remove('show');apply();}
  document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',end,true);document.addEventListener('keydown',e=>{if(e.key==='Enter'&&state.editing){e.preventDefault();e.stopPropagation();commit();}},true);window.addEventListener('mosuan:coordinate',()=>{if(state.editing)render();else renderAppliedMask();});window.MosuanCrop={enter,commit,cancel,restore,render,get state(){return {...state}}};
})();

(() => {
  const state={editing:false,applied:false,x:.02,y:.02,w:.16,h:.16,color:'rgba(26,26,26,.98)',draft:null};let overlay=null,box=null,toolbar=null,mode=null,start=null,original=null;
  function ensure(){if(overlay)return;overlay=document.createElement('div');overlay.className='mosuan-mask-ui';box=document.createElement('div');box.className='mosuan-mask-box';['nw','ne','sw','se'].forEach(n=>{const h=document.createElement('div');h.className='mosuan-mask-handle handle-'+n;h.dataset.handle=n;box.appendChild(h);h.addEventListener('pointerdown',startHandle,true);});box.addEventListener('pointerdown',startMove,true);box.addEventListener('dblclick',commit,true);toolbar=document.createElement('div');toolbar.className='mosuan-mask-toolbar';toolbar.innerHTML='<button data-a="apply">确定遮罩</button><button data-a="restore">恢复头像</button><button data-a="cancel">取消</button>';toolbar.onclick=e=>{const a=e.target?.dataset?.a;if(a==='apply')commit();if(a==='restore')restore();if(a==='cancel')cancel();};overlay.append(box,toolbar);MosuanCoord.ensure().appendChild(overlay);}
  function render(){if(!overlay)return;const layer=MosuanCoord.ensure();if(overlay.parentElement!==layer)layer.appendChild(overlay);const s=state.draft||state;overlay.style.inset='0';box.style.left=s.x*100+'%';box.style.top=s.y*100+'%';box.style.width=s.w*100+'%';box.style.height=s.h*100+'%';}
  function startMove(e){if(!state.editing||e.target!==box)return;mode='move';start={x:e.clientX,y:e.clientY};original={...state.draft};e.preventDefault();e.stopPropagation();}function startHandle(e){if(!state.editing)return;mode=e.currentTarget.dataset.handle;start={x:e.clientX,y:e.clientY};original={...state.draft};e.preventDefault();e.stopPropagation();}
  function move(e){if(!mode||!start||!original||!state.editing)return;const r=MosuanCoord.rect();if(!r)return;const dx=(e.clientX-start.x)/r.width,dy=(e.clientY-start.y)/r.height,min=.02;let s={...original};if(mode==='move'){s.x=Math.max(0,Math.min(1-s.w,original.x+dx));s.y=Math.max(0,Math.min(1-s.h,original.y+dy));}else{if(mode.includes('w')){const right=original.x+original.w,nx=Math.max(0,Math.min(right-min,original.x+dx));s.x=nx;s.w=right-nx;}if(mode.includes('e')){const right=Math.max(original.x+min,Math.min(1,original.x+original.w+dx));s.w=right-original.x;}if(mode.includes('n')){const bottom=original.y+original.h,ny=Math.max(0,Math.min(bottom-min,original.y+dy));s.y=ny;s.h=bottom-ny;}if(mode.includes('s')){const bottom=Math.max(original.y+min,Math.min(1,original.y+original.h+dy));s.h=bottom-original.y;}}state.draft=s;render();}
  function end(){mode=null;start=null;original=null;}function maskElement(){const layer=MosuanCoord.ensure();let m=layer.querySelector('.mosuan-video-mask');if(!m){m=document.createElement('div');m.className='mosuan-video-mask';layer.appendChild(m);}return m;}function apply(){const m=maskElement();if(!state.applied){m.style.display='none';return;}m.style.display='block';m.style.left=state.x*100+'%';m.style.top=state.y*100+'%';m.style.width=state.w*100+'%';m.style.height=state.h*100+'%';m.style.background=state.color;}function enter(){ensure();state.editing=true;state.draft={x:state.x,y:state.y,w:state.w,h:state.h};overlay.classList.add('show');render();}function commit(){if(!state.editing)return;Object.assign(state,state.draft||{});state.draft=null;state.editing=false;state.applied=true;overlay.classList.remove('show');apply();}function cancel(){state.draft=null;state.editing=false;overlay?.classList.remove('show');}function restore(){state.applied=false;state.draft=null;state.editing=false;overlay?.classList.remove('show');apply();}document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',end,true);document.addEventListener('keydown',e=>{if(e.key==='Enter'&&state.editing){e.preventDefault();e.stopPropagation();commit();}},true);window.addEventListener('mosuan:coordinate',()=>{if(state.editing)render();apply();});window.MosuanMask={enter,commit,cancel,restore,render,get state(){return {...state}}};
})();

(() => {document.addEventListener('keydown',e=>{const t=e.target;if(t&&(t.tagName==='INPUT'||t.tagName==='TEXTAREA'||t.isContentEditable))return;const p=window.MosuanPlayer;if(!p||!p.video)return;let h=true;switch(e.key){case ' ':p.playPause();break;case 'ArrowLeft':p.seek(e.shiftKey?-10:-5);break;case 'ArrowRight':p.seek(e.shiftKey?10:5);break;case '[':p.changeRate(-1);break;case ']':p.changeRate(1);break;case '0':p.setRate(1);break;case 'm':case 'M':p.mute();break;case 'r':case 'R':MosuanInvert.toggle();break;case 'c':case 'C':MosuanCrop.enter();break;case 'a':case 'A':MosuanMask.enter();break;case 'Escape':MosuanCrop.cancel();MosuanMask.cancel();break;default:h=false;}if(h){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();}},true);})();

(() => {let last=null;function scan(){const v=MosuanPlayer.findVideo();if(v&&v!==last){last=v;MosuanPlayer.bind(v);}MosuanCoord.render();}scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});setInterval(scan,700);})();
