name: Screenbox Player Build

on:
  push:
    branches:
      - screenbox-player
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - name: Cache NuGet packages
        uses: actions/cache@v6
        with:
          path: ~\.nuget\packages
          key: ${{ runner.os }}-nuget-screenbox-${{ hashFiles('Screenbox/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-screenbox-

      - name: Update package manifest
        shell: pwsh
        run: .\Screenbox\scripts\Update-AppxManifest.ps1 -Identity SideloadUnsigned

      - name: Update project version
        shell: pwsh
        run: .\Screenbox\scripts\Update-ProjectVersion.ps1

      - name: Build app package
        shell: pwsh
        env:
          PackageDir: C:\DeployOutput\
        run: |
          msbuild Screenbox\Screenbox\Screenbox.csproj `
            -restore `
            -p:RestoreConfigFile=Screenbox\nuget.config `
            -p:ContinuousIntegrationBuild=true `
            -p:Configuration=Release `
            -p:Platform=x64 `
            -p:AppxPackageDir=$env:PackageDir `
            -p:UapAppxPackageBuildMode=SideloadOnly

      - name: Upload sideload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Screenbox-sideload-x64
          path: |
            C:\DeployOutput\*_Test\
            !C:\DeployOutput\*_Test\*.msix
          compression-level: 0
          if-no-files-found: error
